version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    command: start-dev
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_IMPORT=/opt/keycloak/data/import/realm-export.json  # ✅ Realm import path
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json